server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pizzeria
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  web:
    resources:
      static-locations: classpath:/static/

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true