server:
  port: 8080

spring:
  application:
    name: ProyectoMarcosApplication

  datasource:
    url: jdbc:mysql://localhost:3306/pizzeria
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  web:
    resources:
      static-locations: classpath:/static/

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true